name: ards
dependencies:
  - python=3.8
  - cython
  - ipython
  - numpy
  - pandas
  - seaborn
  - scipy
  - scikit-learn
  - pathlib
  - matplotlib
  - pyqt
  - jupyter
  - ipython
  - pip
  - pip:
    - coloredlogs
    - pathlib
    - git+git://github.com/lukauskas/dtwco.git#egg=dtwco
    - prettytable
    - tabulate
    - ventmap>=1.5.3
    - imbalanced-learn
