name: aim1ards
dependencies:
  - python=2.7
  - cython
  - ipython
  - numpy
  - pandas
  - pytorch=1.0
  - torchvision
  - cudatoolkit
  - seaborn
  - scipy>=1.1
  - scikit-learn
  - opencv
  - pathlib
  - matplotlib
  - pyqt
  - jupyter
  - ipython
  - statsmodels
  - pyyaml
  - pip
  - pip:
    - coloredlogs
    - pathlib
    - ucdpvanalysis-1.5.tar.gz
    - git+git://github.com/lukauskas/dtwco.git#egg=dtwco
    - prettytable
    - tabulate
    - shap<0.29
    - ventmode-1.0.tar.gz
